// Generated by gencpp from file commande_baxter/bool_state.msg
// DO NOT EDIT!


#ifndef COMMANDE_BAXTER_MESSAGE_BOOL_STATE_H
#define COMMANDE_BAXTER_MESSAGE_BOOL_STATE_H

#include <ros/service_traits.h>


#include <commande_baxter/bool_stateRequest.h>
#include <commande_baxter/bool_stateResponse.h>


namespace commande_baxter
{

struct bool_state
{

typedef bool_stateRequest Request;
typedef bool_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bool_state
} // namespace commande_baxter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commande_baxter::bool_state > {
  static const char* value()
  {
    return "6cc0de94f8bfe875bfa836356ccb5c41";
  }

  static const char* value(const ::commande_baxter::bool_state&) { return value(); }
};

template<>
struct DataType< ::commande_baxter::bool_state > {
  static const char* value()
  {
    return "commande_baxter/bool_state";
  }

  static const char* value(const ::commande_baxter::bool_state&) { return value(); }
};


// service_traits::MD5Sum< ::commande_baxter::bool_stateRequest> should match 
// service_traits::MD5Sum< ::commande_baxter::bool_state > 
template<>
struct MD5Sum< ::commande_baxter::bool_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::commande_baxter::bool_state >::value();
  }
  static const char* value(const ::commande_baxter::bool_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande_baxter::bool_stateRequest> should match 
// service_traits::DataType< ::commande_baxter::bool_state > 
template<>
struct DataType< ::commande_baxter::bool_stateRequest>
{
  static const char* value()
  {
    return DataType< ::commande_baxter::bool_state >::value();
  }
  static const char* value(const ::commande_baxter::bool_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commande_baxter::bool_stateResponse> should match 
// service_traits::MD5Sum< ::commande_baxter::bool_state > 
template<>
struct MD5Sum< ::commande_baxter::bool_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commande_baxter::bool_state >::value();
  }
  static const char* value(const ::commande_baxter::bool_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande_baxter::bool_stateResponse> should match 
// service_traits::DataType< ::commande_baxter::bool_state > 
template<>
struct DataType< ::commande_baxter::bool_stateResponse>
{
  static const char* value()
  {
    return DataType< ::commande_baxter::bool_state >::value();
  }
  static const char* value(const ::commande_baxter::bool_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMANDE_BAXTER_MESSAGE_BOOL_STATE_H
