// Generated by gencpp from file commande_baxter/bool_stateResponse.msg
// DO NOT EDIT!


#ifndef COMMANDE_BAXTER_MESSAGE_BOOL_STATERESPONSE_H
#define COMMANDE_BAXTER_MESSAGE_BOOL_STATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande_baxter
{
template <class ContainerAllocator>
struct bool_stateResponse_
{
  typedef bool_stateResponse_<ContainerAllocator> Type;

  bool_stateResponse_()
    : state(false)  {
    }
  bool_stateResponse_(const ContainerAllocator& _alloc)
    : state(false)  {
    }



   typedef uint8_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::commande_baxter::bool_stateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande_baxter::bool_stateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct bool_stateResponse_

typedef ::commande_baxter::bool_stateResponse_<std::allocator<void> > bool_stateResponse;

typedef boost::shared_ptr< ::commande_baxter::bool_stateResponse > bool_stateResponsePtr;
typedef boost::shared_ptr< ::commande_baxter::bool_stateResponse const> bool_stateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande_baxter::bool_stateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande_baxter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande_baxter::bool_stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_baxter::bool_stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_baxter::bool_stateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::commande_baxter::bool_stateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande_baxter/bool_stateResponse";
  }

  static const char* value(const ::commande_baxter::bool_stateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n\
\n\
";
  }

  static const char* value(const ::commande_baxter::bool_stateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct bool_stateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande_baxter::bool_stateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande_baxter::bool_stateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_BAXTER_MESSAGE_BOOL_STATERESPONSE_H
